spring:
  application:
    name: db-rest-api
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: law_order_schema
    url: jdbc:postgresql://localhost:5432/law-test-db
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080


